name: pulsar-lst1
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - astropy
  - conda-forge::nbsphinx
  - conda-forge::ctapipe~=0.19.2
  - conda-forge::gammapy~=1.1
  - cython
  - graphviz
  - h5py
  - iminuit>=2
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib~=3.7
  - numba
  - numpy=1.21
  - numpydoc
  - protozfits=2.0
  - protobuf=3.20
  - pandas
  - pre-commit
  - psutil
  - pyyaml
  - scipy
  - setuptools
  - sphinx=4.2
  - sphinx-automodapi
  - sphinx_rtd_theme
  - tqdm
  - traitlets
  - vitables
  - jplephem
  - wheel
  - xz
  - zlib
  - zstandard
  - conda-forge::eventio>=1.9.1,<2.0.0a0
  - pip:
      - lstchain~=0.10.6
      - pint-pulsar<=0.9.7
      - more-itertools
